package bd.org.quantum.education.admission.applicant;

import bd.org.quantum.authorizer.helper.UserContext;
import bd.org.quantum.common.utils.DateUtils;
import bd.org.quantum.common.utils.Image;
import bd.org.quantum.common.utils.ImageService;
import bd.org.quantum.common.utils.Misc;
import bd.org.quantum.education.common.Constants;
import bd.org.quantum.education.common.ReportData;
import bd.org.quantum.education.common.ReportHeader;
import bd.org.quantum.education.common.ReportType;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.time.LocalDate;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
public class ApplicantReportService {
    private final ImageService imageService;
    private final ApplicantReportDao applicantReportDao;

    public ApplicantReportService(ImageService imageService, ApplicantReportDao applicantReportDao) {
        this.imageService = imageService;
        this.applicantReportDao = applicantReportDao;
    }

    public ReportData generateApplicantReports(ApplicantReportCriteria criteria) {
        Map<String, Object> result = new LinkedHashMap<>();

        String department = "Shikka Sheba";
        String title = Misc.getReadableName(criteria.getReportType());
        String subTitle = criteria.getIsAdmitted() != null && criteria.getIsAdmitted() ?  "Admitted" : "All (Admitted & Others)";
        String duration = criteria.getSession() == null ? "2001-"+ LocalDate.now().getYear() : criteria.getSession();
        String pageSize = "";
        String orientation = Constants.PAGE_LANDSCAPE;
        String view = "";

        if (ReportType.APPLICANT_LIST.name().equals(criteria.getReportType())) {
            List<Applicant> applicantList = applicantReportDao.getApplicantList(criteria);

            applicantList.forEach(applicant -> {
                if (!StringUtils.isEmpty(applicant.getImagePath())) {
                    Image image = imageService.downloadImg(applicant.getImagePath());
                    applicant.setBase64(image.getData());
                }
            });

            result.put("data", applicantList);
            view = "applicant-report-list";
        }
        return new ReportData(new ReportHeader(department, title, subTitle, duration), getFooterText(), orientation, pageSize, view, result);
    }

    private String getFooterText(){
        String currentDateTime = DateUtils.formatToDDMMYYYYHHMMSSA(new Date());
        return String.format("Generated By %s on %s", UserContext.getPrincipal().getUserDetails().getName(), currentDateTime);
    }
}
